service: sls-koa-api
frameworkVersion: '>=1.1.0 <= 2.2.0'
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-s3-local
  - serverless-offline-sns
  - serverless-secrets-plugin
  - sls-plugin-dynamodb-offline

provider:
  name: aws
  runtime: nodejs12.x

  environment:
    STAGE: dev
    GOOGLE_MAPS_API_KEY: key1188

functions:
  koa:
    handler: sls/koa.ts
    events:
      - http:
          path: first
          method: GET
      - http:
          path: second
          method: POST

#custom:
#  tableName: 'users-tb-${self:provider.stage}'
#  defaults:
#    dynamoDbTableDeletionPolicy: >-
#      ${self:custom.secrets.DB_TABLES_DELETION_POLICY,
#      self:provider.environment.DB_TABLES_DELETION_POLICY}
#    stage: local
#    ports:
#      dynamodb: "2525"
#      sls: "3030"
#      sns: "3535"
#      s3: "4040"
#  dynamodb:
#    start:
#      dbPath: /usr/local/tmp/sls-koa-api
#      delayTransientStatuses: true # More real life experience
#      migrate: true # Create tables after startup
#      port: "${self:custom.defaults.ports.dynamodb}"
#      sharedDb: true # Necessary for the local instances to work correctly
#      stream:
#        readInterval: 1000
#resources:
#  Resources:
#    UsersDynamoDBTable:
#      Type: 'AWS::DynamoDB::Table'
#      Properties:
#        AttributeDefinitions:
#          -
#            AttributeName: userID
#            AttributeType: S
#        KeySchema:
#          -
#            AttributeName: userID
#            KeyType: HASH
#        ProvisionedThroughput:
#          ReadCapacityUnits: 1
#          WriteCapacityUnits: 1
#        TableName: ${self:custom.tableName}
